"""상태 값과 허용 전이."""

from enum import StrEnum


class RunStatus(StrEnum):
    """load_run.status. ck_load_run_status 제약과 같은 값."""

    CREATED = "CREATED"
    EXTRACTING = "EXTRACTING"
    EXTRACTED_VALIDATED = "EXTRACTED_VALIDATED"
    STAGE_VALIDATING = "STAGE_VALIDATING"
    STAGING_VALIDATED = "STAGING_VALIDATED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    SUCCESS = "SUCCESS"
    FAILED_MANIFEST = "FAILED_MANIFEST"
    FAILED_EXTRACT = "FAILED_EXTRACT"
    FAILED_STAGE_VALIDATION = "FAILED_STAGE_VALIDATION"
    FAILED_PUBLISH = "FAILED_PUBLISH"
    PUBLISH_UNKNOWN = "PUBLISH_UNKNOWN"
    FAILED_TARGET_VALIDATION = "FAILED_TARGET_VALIDATION"
    FAILED_SNAPSHOT_EXPIRED = "FAILED_SNAPSHOT_EXPIRED"
    TIMED_OUT = "TIMED_OUT"


class PartitionStatus(StrEnum):
    """load_partition.status."""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRY = "RETRY"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


# POST /runs/{id}/fail 로 허용하는 (기대 상태, 실패 상태). 파티션 실패는 별도 엔드포인트.
ALLOWED_RUN_FAILURES: frozenset[tuple[RunStatus, RunStatus]] = frozenset({
    (RunStatus.CREATED, RunStatus.FAILED_MANIFEST),
    (RunStatus.EXTRACTING, RunStatus.FAILED_EXTRACT),
    (RunStatus.STAGE_VALIDATING, RunStatus.FAILED_STAGE_VALIDATION),
    (RunStatus.STAGING_VALIDATED, RunStatus.FAILED_PUBLISH),
    (RunStatus.PUBLISHED, RunStatus.FAILED_TARGET_VALIDATION),
})

# 이 오류로 파티션이 실패하면 run을 FAILED_SNAPSHOT_EXPIRED로 바꾼다(같은 SCN으로 다시 읽을 수 없음).
SNAPSHOT_ERROR_CODES = frozenset({"ORA-01555", "ORA-08180"})

# 정리(PG-70) 대상이 되는 끝난 상태. PUBLISH_UNKNOWN은 운영자가 확정하기 전까지 끝난 상태가 아니다.
CLEANUP_SUCCESS_STATUSES = frozenset({RunStatus.SUCCESS})
CLEANUP_FAILED_STATUSES = frozenset({
    RunStatus.FAILED_MANIFEST, RunStatus.FAILED_EXTRACT, RunStatus.FAILED_STAGE_VALIDATION,
    RunStatus.FAILED_PUBLISH, RunStatus.FAILED_TARGET_VALIDATION, RunStatus.FAILED_SNAPSHOT_EXPIRED,
    RunStatus.TIMED_OUT})
