from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "CREATED"
    EXTRACTING = "EXTRACTING"
    EXTRACTED_VALIDATED = "EXTRACTED_VALIDATED"
    STAGE_VALIDATING = "STAGE_VALIDATING"
    STAGING_VALIDATED = "STAGING_VALIDATED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    SUCCESS = "SUCCESS"
    FAILED_MANIFEST = "FAILED_MANIFEST"
    FAILED_EXTRACT = "FAILED_EXTRACT"
    FAILED_STAGE_VALIDATION = "FAILED_STAGE_VALIDATION"
    FAILED_PUBLISH = "FAILED_PUBLISH"
    PUBLISH_UNKNOWN = "PUBLISH_UNKNOWN"
    FAILED_TARGET_VALIDATION = "FAILED_TARGET_VALIDATION"
    FAILED_SNAPSHOT_EXPIRED = "FAILED_SNAPSHOT_EXPIRED"
    TIMED_OUT = "TIMED_OUT"


class PartitionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRY = "RETRY"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


# POST /runs/{id}/fail 로 허용하는 (기대 상태, 실패 상태). 파티션 실패는 별도 엔드포인트.
ALLOWED_RUN_FAILURES: frozenset[tuple[RunStatus, RunStatus]] = frozenset({
    (RunStatus.CREATED, RunStatus.FAILED_MANIFEST),
    (RunStatus.EXTRACTING, RunStatus.FAILED_EXTRACT),
    (RunStatus.STAGE_VALIDATING, RunStatus.FAILED_STAGE_VALIDATION),
    (RunStatus.STAGING_VALIDATED, RunStatus.FAILED_PUBLISH),
    (RunStatus.PUBLISHED, RunStatus.FAILED_TARGET_VALIDATION),
})

SNAPSHOT_ERROR_CODES = frozenset({"ORA-01555", "ORA-08180"})
